<a href="https://colab.research.google.com/github/alifele/Machine_learning/blob/master/%20Little_functions/train_test_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.model_selection import train_test_split


``` sklearn.model_selection.train_test_split ``` can devide iou data base into test and train subsets. The relative size of subsets can be set by the argomans

In [6]:
X = np.arange(10).reshape((5,2))
y = list(range(5))
print('the X is: \n {}'.format(X))
print('the y is: \n {}'.format(y))



the X is: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
the y is: 
 [0, 1, 2, 3, 4]


#Implementing the function


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=42,shuffle=False)
#note that the default value for test_size is 0.25
print("X_train is: \n{}\n\n".format(X_train))
print("y_train is: \n{}\n\n".format(y_train))
print("X_test is: \n{}\n\n".format(X_test))
print("y_test is: \n{}\n\n".format(y_test))

X_train is: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


y_train is: 
[0, 1, 2, 3]


X_test is: 
[[8 9]]


y_test is: 
[4]


