<a href="https://colab.research.google.com/github/alifele/Machine_learning/blob/master/Little_functions%26Little_Tricks/Confusion_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to use th sklearn confusion matrix

In [0]:
from sklearn.metrics import confusion_matrix
import numpy as np

In [0]:
actual = np.array([1,2,1,1,2,1,2,2,2,1,3,3,2,1,2,3])
predict= np.array([1,1,2,1,2,1,1,1,2,2,1,3,3,1,2,3])

In [5]:
cm = confusion_matrix(actual, predict)
print(cm)

[[4 2 0]
 [3 3 1]
 [1 0 2]]


this matrix is the matix of 

| *was 1 and predicted as 1*  ||  was 1 but predicted as 2  || was 1 but predicted as 3|
|----||---||------|
| was 2 but predicted as 1  || *was 2 and predicted as 2*  || was 2 but predicted as 3|
| was 3 but predicted as 1 ||was 3 but predicted as 2 || *was 3 and predicted as 3*|
