<a href="https://colab.research.google.com/github/alifele/Machine_learning/blob/master/Neural_Networks/Hand_made_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Simple hand_made Neural network
in this note book i am going to define a simple but made nural network

* three layers 
   * Input layer -----> number if features 
   * Layer <sub>[2]</sub> ----> three nodes
   * Layer<sub>[3]</sub> -----> two nodes
   * Layer<sub>[4]</sub>----->one node

In [0]:
import numpy as np
import matplotlib.pyplot as plt

#Defining and Initializing weights parameters

In [0]:
n_f = 4 # number of features
n_l1 = n_f #the number of nodes in layer 0 is the number of features
n_l2 = 3 # number of nodes in layer 1
n_l3 = 2 # number of nodes in layer 2
n_l4 = 1 # number of nodes in layer 3
W2 = np.ones((n_l2, n_l1)) 
W3 = np.ones((n_l3, n_l2))
W4 = np.ones((n_l4, n_l3))

B2 = np.zeros((n_l2, 1))
B3 = np.zeros((n_l3, 1))
B4 = np.zeros((n_l4, 1))
W = [W2, W3, W4]   # the list of weights for each layer
B = [B2, B3, B3]   # the list of biases for each layer 


#Function A and Z of layers


In [0]:
A_2 = [0, 0, 0]   # np.array((0,0,0))
A_3 = [0, 0]   #np.array((0,0))
A_4 = [0]   #np.array((0))

A = [A_2, A_3, A_4]
def sigmoid(X):
  Z = 1/(1+np.exp(-X))
  return Z
Z_2 = sigmoid(np.array(A_2))
Z_3 = sigmoid(np.array(A_3))
Z_4 = sigmoid(np.array(A_4))

Z = [Z_2, Z_3, Z_4]








#Data generation 

In [0]:
Data = np.random.random((2000,n_f)) *10

#Dynamic of Neural Network

# the first layer

In [23]:

for elem in A: 
  j = 0
  i = 0
  for element in elem :
    elem[i] = Data[10]* W[j][i].T
    i = i+1
  j = j+1
  
  
A

[[array([4.40807028, 2.44174531, 6.54163949, 1.19175058]),
  array([4.40807028, 2.44174531, 6.54163949, 1.19175058]),
  array([4.40807028, 2.44174531, 6.54163949, 1.19175058])],
 [array([4.40807028, 2.44174531, 6.54163949, 1.19175058]),
  array([4.40807028, 2.44174531, 6.54163949, 1.19175058])],
 [array([4.40807028, 2.44174531, 6.54163949, 1.19175058])]]

In [0]:
(for weight in W : 